arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
# output-dir defaults to lib/generated for non-synthetic
# nullable-getter defaults to false
# untranslated-messages-file is optional
