name: f35_flight_compensation
description: >-
  A cross-platform Flutter app to automatically detect flights and help users claim compensation under EC261/2004.
version: 0.1.0
publish_to: 'none'
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Added Flutter localization packages
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  provider: ^6.1.1
  geolocator: ^10.1.0
  sensors_plus: ^4.0.2
  http: ^1.2.1
  pdf: ^3.10.8
  # Temporarily disabled due to Android resource linking issues
  # printing: ^5.11.0
  image_picker: ^1.0.7
  flutter_local_notifications: ^19.1.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2

  # Added for dependency injection - MVVM architecture
  get_it: ^7.6.7
  # Document scanning and OCR
  google_mlkit_text_recognition: ^0.11.0
  path_provider: ^2.1.2
  image: ^4.0.17
  camera: ^0.10.5+9
  crop_image: ^1.0.11
  # Push notifications
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  firebase_messaging: ^14.9.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0

  # Charts for dashboard
  fl_chart: ^0.64.0
  # Improved error handling
  dio: ^5.3.3
  # Animations
  flutter_animate: ^4.2.0
  # Enhanced UI
  shimmer: ^3.0.0
  collection: ^1.19.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9

flutter:
  uses-material-design: true

  # Enable generation of localized strings
  generate: true
  assets:
    - lib/data/airline_claim_procedures.json
    - assets/lib/data/iata_codes.json
    - assets/rapidapi_key.txt
    - assets/data/eu_airports.json
    - assets/data/flight_compensation_data.json
    - assets/images/
    - lib/l10n/
