// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzHL1-AKanmYSCHn3ojzNVM3dw6zld1OY',
    appId: '1:445502709010:web:654d1de7c56da0d42667cb',
    messagingSenderId: '445502709010',
    projectId: 'flightcompensation-d059a',
    authDomain: 'flightcompensation-d059a.firebaseapp.com',
    storageBucket: 'flightcompensation-d059a.firebasestorage.app',
    measurementId: 'G-3B4RKCVJX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7KBknrq-wODQGwLRM6TIvVzT3GfQb2Kg',
    appId: '1:445502709010:android:5d4ddd41072a6f6b2667cb',
    messagingSenderId: '445502709010',
    projectId: 'flightcompensation-d059a',
    storageBucket: 'flightcompensation-d059a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Svkofn0W3Tc3MrHNOarZ3g8_xrqIX_Q',
    appId: '1:445502709010:ios:73ff98f8d298613e2667cb',
    messagingSenderId: '445502709010',
    projectId: 'flightcompensation-d059a',
    storageBucket: 'flightcompensation-d059a.firebasestorage.app',
    androidClientId: '445502709010-085esmp9bjqf0jufr7gr75n7cnd6lrb2.apps.googleusercontent.com',
    iosClientId: '445502709010-t97uh4g0hdu7d90inpqcsrtcobm5tt9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.f35FlightCompensation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Svkofn0W3Tc3MrHNOarZ3g8_xrqIX_Q',
    appId: '1:445502709010:ios:73ff98f8d298613e2667cb',
    messagingSenderId: '445502709010',
    projectId: 'flightcompensation-d059a',
    storageBucket: 'flightcompensation-d059a.firebasestorage.app',
    androidClientId: '445502709010-085esmp9bjqf0jufr7gr75n7cnd6lrb2.apps.googleusercontent.com',
    iosClientId: '445502709010-t97uh4g0hdu7d90inpqcsrtcobm5tt9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.f35FlightCompensation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzHL1-AKanmYSCHn3ojzNVM3dw6zld1OY',
    appId: '1:445502709010:web:e3d2edf0b3d271992667cb',
    messagingSenderId: '445502709010',
    projectId: 'flightcompensation-d059a',
    authDomain: 'flightcompensation-d059a.firebaseapp.com',
    storageBucket: 'flightcompensation-d059a.firebasestorage.app',
    measurementId: 'G-EFFJ9FJM6C',
  );
}
