import 'package:flutter/material.dart';
import '../core/app_localizations_patch.dart'; // Import for safe l10n extension
import '../services/aviation_stack_service.dart';
import 'claim_submission_screen.dart';
import '../models/claim.dart';

import 'package:flutter/foundation.dart' as foundation;
import 'package:intl/intl.dart';
import 'dart:math' as math;


class EUEligibleFlightsScreen extends StatefulWidget {
  const EUEligibleFlightsScreen({super.key});

  @override
  State<EUEligibleFlightsScreen> createState() => _EUEligibleFlightsScreenState();
}

class _EUEligibleFlightsScreenState extends State<EUEligibleFlightsScreen> {
  late Future<List<Map<String, dynamic>>> _flightsFuture;
  String _carrierFilter = '';
  static const int _hoursFilter = 72;

  @override
  void initState() {
    super.initState();
    _flightsFuture = _loadFlights();
  }

  Future<List<Map<String, dynamic>>> _loadFlights() async {
    foundation.debugPrint('Attempting to load EU compensation eligible flights for the last $_hoursFilter hours...');
            final service = AviationStackService(
              baseUrl: 'https://piotrs.pythonanywhere.com',
              usingPythonBackend: true,
              pythonBackendUrl: 'https://piotrs.pythonanywhere.com',
            );

    try {
      final flights = await service.getEUCompensationEligibleFlights(hours: _hoursFilter);
      foundation.debugPrint('Successfully loaded ${flights.length} eligible flights.');
      return flights;
    } catch (e) {
      foundation.debugPrint('Error loading flights in _loadFlights: $e');
      // Propagate the error to be handled by the FutureBuilder.
      throw Exception('Failed to load flight data: $e');
    }
  }

  void _refreshFlights() {
    setState(() {
      _flightsFuture = _loadFlights();
    });
  }

  int _calculateDelayMinutes(Map<String, dynamic> scheduled, Map<String, dynamic> actual) {
    try {
      final scheduledStr = scheduled['utc'] ?? scheduled['local'];
      final actualStr = actual['utc'] ?? actual['local'];
      
      if (scheduledStr != null && actualStr != null) {
        final scheduledTime = DateTime.parse(scheduledStr);
        final actualTime = DateTime.parse(actualStr);
        return actualTime.difference(scheduledTime).inMinutes;
      }
    } catch (e) {
      foundation.debugPrint('Error calculating delay: $e');
    }
    return 0;
  }
  
  void _openCompensationForm(BuildContext context, Map<String, dynamic> flight) {
    // Create an initial Claim object from the flight data
    final String departureTimeStr = flight['departure_scheduled_time']?.toString() ?? '';
    DateTime? departureDate;
    if (departureTimeStr.isNotEmpty) {
      try {
        departureDate = DateTime.parse(departureTimeStr);
      } catch (e) {
        foundation.debugPrint('Error parsing departure date: $e. Fallback to now.');
        departureDate = DateTime.now();
      }
    } else {
      departureDate = DateTime.now();
    }

    final initialClaim = Claim(
      id: '', // Will be generated by backend
      userId: '', // Will be added from auth service later
      airlineName: flight['airline_name']?.toString() ?? 'Unknown Airline',
      flightNumber: flight['flight_iata']?.toString() ?? '',
      departureAirport: flight['departure_airport_iata']?.toString() ?? '',
      arrivalAirport: flight['arrival_airport_iata']?.toString() ?? '',
      flightDate: departureDate,
      reason: '', // To be filled by user in the next steps
      compensationAmount: 0, // To be calculated
      status: 'Draft', // Initial status
      bookingReference: '', // To be filled by user
      attachmentUrls: [],
    );

    // Navigate to the new multi-step claim submission screen
    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) => ClaimSubmissionScreen(initialClaim: initialClaim),
      ),
    );
  }

  String _getCompensationAmount(Map<String, dynamic> flight) {
    final int amount = _calculateCompensationAmount(flight);
    
    if (amount <= 0) {
      return 'Eligible (calculation needed)';
    }
    
    return '€$amount';
  }

  int _calculateCompensationAmount(Map<String, dynamic> flight) {
    try {
      if (flight.containsKey('potentialCompensationAmount') && 
          flight['potentialCompensationAmount'] is num && 
          flight['potentialCompensationAmount'] > 0) {
        return flight['potentialCompensationAmount'].toInt();
      }
      
      final distance = flight['distance'] as int? ?? _estimateFlightDistance(flight);
      
      if (distance <= 1500) {
        return 250; // Short flights up to 1500 km: €250
      } else if (distance <= 3500) {
        return 400; // Medium flights 1500-3500 km: €400
      } else {
        return 600; // Long flights over 3500 km: €600
      }
    } catch (e) {
      foundation.debugPrint('Error calculating compensation amount: $e');
      return 0;
    }
  }

  int _estimateFlightDistance(Map<String, dynamic> flight) {
    try {
      final departureIata = flight['departure_airport_iata']?.toString() ?? '';
      final arrivalIata = flight['arrival_airport_iata']?.toString() ?? '';
      
      if (departureIata.isEmpty || arrivalIata.isEmpty) {
        return 1000; // Default to short-haul if no airport data
      }
      
      // Calculate distance based on airport coordinates
      final distance = _calculateAirportDistance(departureIata, arrivalIata);
      return distance;
    } catch (e) {
      foundation.debugPrint('Error estimating flight distance: $e');
      return 1000; // Default to short-haul on error
    }
  }
  
  int _calculateAirportDistance(String departureIata, String arrivalIata) {
    // Major European and international airport coordinates (lat, lng)
    final Map<String, List<double>> airportCoordinates = {
      // Major EU hubs
      'LHR': [51.4700, -0.4543],   // London Heathrow
      'CDG': [49.0097, 2.5479],    // Paris Charles de Gaulle
      'FRA': [50.0379, 8.5622],    // Frankfurt
      'AMS': [52.3105, 4.7683],    // Amsterdam Schiphol
      'MAD': [40.4839, -3.5680],   // Madrid
      'FCO': [41.8003, 12.2389],   // Rome Fiumicino
      'MUC': [48.3537, 11.7750],   // Munich
      'ZUR': [47.4647, 8.5492],    // Zurich
      'VIE': [48.1103, 16.5697],   // Vienna
      'CPH': [55.6180, 12.6506],   // Copenhagen
      'ARN': [59.6519, 17.9186],   // Stockholm Arlanda
      'OSL': [60.1939, 11.1004],   // Oslo
      'HEL': [60.3172, 24.9633],   // Helsinki
      'WAW': [52.1657, 20.9671],   // Warsaw
      'PRG': [50.1008, 14.2632],   // Prague
      'BUD': [47.4298, 19.2611],   // Budapest
      'ATH': [37.9364, 23.9445],   // Athens
      'LIS': [38.7813, -9.1363],   // Lisbon
      'BCN': [41.2974, 2.0833],    // Barcelona
      'MXP': [45.6306, 8.7281],    // Milan Malpensa
      'DUB': [53.4213, -6.2701],   // Dublin
      'BRU': [50.9014, 4.4844],    // Brussels
      
      // Additional European airports
      'LGW': [51.1481, -0.1903],   // London Gatwick
      'STN': [51.8860, 0.2389],    // London Stansted
      'LTN': [51.8747, -0.3683],   // London Luton
      'ORY': [48.7233, 2.3794],    // Paris Orly
      'DUS': [51.2895, 6.7668],    // Düsseldorf
      'HAM': [53.6304, 9.9882],    // Hamburg
      'STR': [48.6899, 9.2219],    // Stuttgart
      'CGN': [50.8659, 7.1427],    // Cologne
      'NUE': [49.4987, 11.0669],   // Nuremberg
      'TXL': [52.5597, 13.2877],   // Berlin Tegel (historical)
      'SXF': [52.3800, 13.5225],   // Berlin Schönefeld
      'BER': [52.3667, 13.5033],   // Berlin Brandenburg
      
      // Major non-EU destinations (for reference)
      'JFK': [40.6413, -73.7781],  // New York JFK
      'LAX': [33.9425, -118.4081], // Los Angeles
      'NRT': [35.7720, 140.3929],  // Tokyo Narita
      'SIN': [1.3644, 103.9915],   // Singapore
      'DXB': [25.2532, 55.3657],   // Dubai
      'DOH': [25.2731, 51.6080],   // Doha
      'IST': [41.2753, 28.7519],   // Istanbul
      'SVO': [55.9726, 37.4146],   // Moscow Sheremetyevo
      'PEK': [40.0799, 116.6031],  // Beijing
      'HKG': [22.3080, 113.9185],  // Hong Kong
    };
    
    final depCoords = airportCoordinates[departureIata];
    final arrCoords = airportCoordinates[arrivalIata];
    
    if (depCoords == null || arrCoords == null) {
      // Fallback: estimate based on common route patterns
      return _estimateDistanceByRoute(departureIata, arrivalIata);
    }
    
    // Calculate great circle distance using Haversine formula
    final distance = _haversineDistance(
      depCoords[0], depCoords[1], 
      arrCoords[0], arrCoords[1]
    );
    
    return distance.round();
  }
  
  double _haversineDistance(double lat1, double lon1, double lat2, double lon2) {
    const double earthRadius = 6371; // Earth's radius in kilometers
    
    final double dLat = _degreesToRadians(lat2 - lat1);
    final double dLon = _degreesToRadians(lon2 - lon1);
    
    final double a = math.sin(dLat / 2) * math.sin(dLat / 2) +
        math.cos(_degreesToRadians(lat1)) * math.cos(_degreesToRadians(lat2)) *
        math.sin(dLon / 2) * math.sin(dLon / 2);
    
    final double c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a));
    
    return earthRadius * c;
  }
  
  double _degreesToRadians(double degrees) {
    return degrees * (math.pi / 180);
  }
  
  int _estimateDistanceByRoute(String departureIata, String arrivalIata) {
    // Fallback estimation based on common route patterns
    final Set<String> longHaulDestinations = {
      'JFK', 'LAX', 'ORD', 'DFW', 'ATL', 'MIA', 'YYZ', 'YVR', // North America
      'NRT', 'ICN', 'PVG', 'PEK', 'HKG', 'SIN', 'BKK', 'DEL', // Asia
      'SYD', 'MEL', 'AKL', // Oceania
      'JNB', 'CAI', 'ADD', // Africa
      'GRU', 'EZE', 'SCL', 'BOG', 'LIM', // South America
    };
    
    final Set<String> mediumHaulDestinations = {
      'IST', 'SVO', 'LED', 'KBP', // Eastern Europe/Russia
      'DXB', 'DOH', 'AUH', 'KWI', 'RUH', // Middle East
      'CAI', 'TUN', 'CMN', 'ALG', // North Africa
      'TLV', 'AMM', 'BEY', // Levant
    };
    
    if (longHaulDestinations.contains(departureIata) || 
        longHaulDestinations.contains(arrivalIata)) {
      return 8000; // Long-haul
    }
    
    if (mediumHaulDestinations.contains(departureIata) || 
        mediumHaulDestinations.contains(arrivalIata)) {
      return 2500; // Medium-haul
    }
    
    // Default to short-haul for intra-European flights
    return 1200;
  }



  Widget _buildErrorWidget(BuildContext context, Object? error) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.cloud_off, size: 60, color: Colors.redAccent),
            const SizedBox(height: 16),
            Text(
              context.l10n.apiConnectionIssue,
              style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            Text(
              error.toString(),
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.grey[600]),
            ),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              icon: const Icon(Icons.refresh),
              label: Text(context.l10n.retry),
              onPressed: _refreshFlights,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyStateWidget(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.flight_land, size: 80, color: Colors.grey),
            const SizedBox(height: 16),
            Text(
              context.l10n.noEligibleFlightsFound,
              style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                fontWeight: FontWeight.bold,
                color: Colors.blueGrey[700],
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              child: Text(
                context.l10n.noEligibleFlightsDescription(_hoursFilter),
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.grey[600]),
              ),
            ),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              icon: const Icon(Icons.refresh),
              label: Text(context.l10n.checkAgain),
              onPressed: _refreshFlights,
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          context.l10n.euWideCompensationEligibleFlights,
          style: const TextStyle(fontSize: 18),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            tooltip: context.l10n.forceRefreshData,
            onPressed: () {
              // Show a snackbar to indicate refresh is happening
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text(context.l10n.forcingFreshDataLoad)),
              );
              // Re-fetch flights using the primary load function
              setState(() {
                _flightsFuture = _loadFlights();
              });
            },
          ),
        ],
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 8.0),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    decoration: InputDecoration(
                      hintText: context.l10n.filterByAirline,
                      prefixIcon: const Icon(Icons.search),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8.0),
                      ),
                      contentPadding: const EdgeInsets.symmetric(vertical: 0),
                    ),
                    onChanged: (value) {
                      setState(() {
                        _carrierFilter = value;
                      });
                    },
                  ),
                ),
                const SizedBox(width: 8),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  decoration: BoxDecoration(
                    color: Colors.grey[200],
                    borderRadius: BorderRadius.circular(24),
                  ),
                  child: Text(
                    context.l10n.lastHours(72),
                    style: TextStyle(fontWeight: FontWeight.w500, color: Colors.grey[700]),
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: FutureBuilder<List<Map<String, dynamic>>>(
              future: _flightsFuture,
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const CircularProgressIndicator(),
                        const SizedBox(height: 20),
                        Text(
                          context.l10n.loadingExternalData,
                          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                                fontWeight: FontWeight.bold,
                              ),
                          textAlign: TextAlign.center,
                        ),
                        const SizedBox(height: 8),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 32),
                          child: Text(
                            context.l10n.loadingExternalDataDescription,
                            style: TextStyle(color: Colors.grey[600]),
                            textAlign: TextAlign.center,
                          ),
                        ),
                      ],
                    ),
                  );
                }

                if (snapshot.hasError) {
                  return _buildErrorWidget(context, snapshot.error);
                }

                if (!snapshot.hasData || snapshot.data!.isEmpty) {
                  return _buildEmptyStateWidget(context);
                }

                final allFlights = snapshot.data!;
                
                // Apply filters
                final List<Map<String, dynamic>> filteredFlights = allFlights.where((flight) {
                  final airlineName = flight['airline_name']?.toString().toLowerCase() ?? '';
                  final passesCarrierFilter = _carrierFilter.isEmpty || airlineName.contains(_carrierFilter.toLowerCase());
                  return passesCarrierFilter;
                }).toList();

                if (filteredFlights.isEmpty) {
                  return Center(
                    child: Text(context.l10n.noFlightsMatchingFilter(_carrierFilter)),
                  );
                }

                return ListView.separated(
                  padding: EdgeInsets.zero,
                  itemCount: filteredFlights.length,
                  separatorBuilder: (context, index) => const Divider(height: 1),
                  itemBuilder: (context, idx) {
                    final flight = filteredFlights[idx];

                    final airlineName = flight['airline_name']?.toString() ?? 'Unknown';
                    final flightNumber = flight['flight_iata']?.toString() ?? '';
                    final aircraftModel = flight['aircraft_registration']?.toString() ?? 'Unknown';
                    final departureTimeStr = flight['departure_scheduled_time']?.toString();
                    final departureTime = (departureTimeStr?.isNotEmpty ?? false) ? 
                        DateTime.parse(departureTimeStr!) : null;
                    final delayMinutes = flight['delay_minutes'] ?? 0;
                    
                    // Determine compensation based on flight data
                    int compensationAmount = 0;
                    if (flight.containsKey('eligibility_details') && 
                        flight['eligibility_details'] != null && 
                        flight['eligibility_details']['estimatedCompensation'] != null) {
                      compensationAmount = flight['eligibility_details']['estimatedCompensation'];
                    } else {
                      // Fallback compensation calculation
                      final distance = flight['distance'] as int? ?? _estimateFlightDistance(flight);
                      if (distance <= 1500) {
                        compensationAmount = 250;
                      } else if (distance <= 3500) {
                        compensationAmount = 400;
                      } else {
                        compensationAmount = 600;
                      }
                    }

                    // Format title with flight number and airline
                    String titleText = flightNumber.isNotEmpty ? 
                        "$flightNumber - $airlineName" : airlineName;

                    return Padding(
                      padding: const EdgeInsets.symmetric(vertical: 4.0),
                      child: Column(
                        children: [
                          // Flight info section
                          Padding(
                            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
                            child: Row(
                              children: [
                                // Airplane icon
                                Container(
                                  padding: const EdgeInsets.all(4),
                                  child: const Icon(Icons.flight, 
                                    size: 32, 
                                    color: Colors.blueGrey,
                                  ),
                                ),
                                const SizedBox(width: 12),
                                // Flight details
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      // Flight number and airline
                                      Row(
                                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                        children: [
                                          Text(
                                            titleText,
                                            style: const TextStyle(
                                              fontWeight: FontWeight.bold,
                                              fontSize: 16,
                                            ),
                                          ),
                                          // EU Compensation tag
                                          Row(
                                            children: [
                                              const Icon(
                                                Icons.check_circle,
                                                color: Colors.green,
                                                size: 18,
                                              ),
                                              const SizedBox(width: 4),
                                              Text(
                                                context.l10n.euCompensation,
                                                style: TextStyle(
                                                  color: Colors.green[600],
                                                  fontSize: 14,
                                                  fontWeight: FontWeight.w500,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 6),
                                      // Scheduled time
                                      Row(
                                        children: [
                                          const Icon(Icons.access_time, size: 14, color: Colors.black54),
                                          const SizedBox(width: 4),
                                          Text(
                                            "${context.l10n.scheduledLabel} ${departureTime != null ? DateFormat('E, MMM d, HH:mm').format(departureTime) : 'N/A'}",
                                            style: const TextStyle(fontSize: 14, color: Colors.black54),
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 4),
                                      // Status with delay
                                      Row(
                                        children: [
                                          const Icon(Icons.info_outline, size: 14, color: Colors.black54),
                                          const SizedBox(width: 4),
                                          Text(
                                            "${context.l10n.statusLabel} ${context.l10n.flightStatusDelayed} - $delayMinutes ${context.l10n.minutes}",
                                            style: TextStyle(
                                              fontSize: 14, 
                                              color: delayMinutes >= 180 ? Colors.red : Colors.orange,
                                              fontWeight: FontWeight.w500,
                                            ),
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 4),
                                      // Compensation amount
                                      Row(
                                        children: [
                                          const Icon(Icons.euro, size: 14, color: Colors.green),
                                          const SizedBox(width: 4),
                                          Text(
                                            "${context.l10n.potentialCompensation} €$compensationAmount",
                                            style: TextStyle(
                                              fontSize: 14,
                                              color: Colors.green[700],
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 4),
                                      // Aircraft model
                                      Row(
                                        children: [
                                          const Icon(Icons.airplanemode_active, size: 14, color: Colors.black54),
                                          const SizedBox(width: 4),
                                          Text(
                                            "${context.l10n.aircraftLabel} $aircraftModel",
                                            style: const TextStyle(fontSize: 14, color: Colors.black54),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                          // Pre-fill button
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16.0, 0, 16.0, 12.0),
                            child: SizedBox(
                              width: double.infinity,
                              child: ElevatedButton.icon(
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: Colors.green,
                                  foregroundColor: Colors.white,
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(24),
                                  ),
                                  padding: const EdgeInsets.symmetric(vertical: 12),
                                ),
                                onPressed: () => _openCompensationForm(context, flight),
                                icon: const Icon(Icons.description, size: 16),
                                label: Text(
                                  context.l10n.prefillCompensationForm, 
                                  style: const TextStyle(fontWeight: FontWeight.w500, fontSize: 14),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
