name: Build Flutter Web and Publish Static

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Fetch dependencies
        run: flutter pub get

      - name: Build Web (release)
        run: flutter build web --release --no-wasm-dry-run

      - name: Prepare static output directory
        run: |
          rm -rf vercel-backend/public || true
          mkdir -p vercel-backend/public
          cp -R build/web/* vercel-backend/public/

      - name: Commit and push static assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Ensure we're up-to-date to avoid non-fast-forward push errors
          git fetch origin main
          git pull --rebase origin main
          git add vercel-backend/public
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: publish Flutter web build to vercel-backend/public [skip ci]"
          # Retry push once if main advanced during this run
          git push origin HEAD:main || (git pull --rebase origin main && git push origin HEAD:main)
